### PR TITLE
template

### PR DESCRIPTION
**Pull request by islipfd19**
This is the template filed used in Jenkins to build each project and to offload the images to the web server. The intent is to allow fellow team members to review it and to build a new simpler mechanism for jenkins to build each project.

This template is to build each nightly and alpha image(s)

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Many thanks for this!

A few (noddy/stream of consciousness) questions to get me (and maybe others) off the ground:

1. The template file is basically a shell script - do we know if it's `sh` or `bash`? I'm guessing it's probably `sh`.

2. Are we in some vague agreement that we'll try and read a config file to determine project/device/arch, and the config file will most likely come from the LibreELEC/LibreELEC.tv repo (maybe `distributions/LibreELEC/jenkins.conf`?) which means it can be branch specific so that we can build different projects/devices/arch for `master` than we might build for `libreelec-9.2` etc..

3. I'm assuming the LibreELEC/LibreELEC.tv repository is already cloned (and any test PR's applied) before this template is executed? In which case the sole job of this template is to generate the `env.properties` file for a single project/device/arch, before running `make image` and (if successful) copying the image & tar files to a remote server.

4. It looks like we are using this same template for releases, nightlies and all other builds started by Jenkins. Not entirely sure I understand the "URL construct" logic in line #194, hopefully we can simplify that somehow (use an external script?)

5. It looks like `${JOB}` controls what is built each time this template is executed. An example `JOB=RK3328` would build only `PROJECT=Rockchip DEVICE=RK3328 ARCH=arm` (so basically, we run this template per-device):
```
Started by an SCM change
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building remotely on build4 (slave LibreELEC LibreELEV.tv) in workspace /var/lib/jenkins/LE/build4/workspace/RK3328
No credentials specified
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git://github.com/LibreELEC/LibreELEC.tv.git # timeout=10
Fetching upstream changes from git://github.com/LibreELEC/LibreELEC.tv.git
 > git --version # timeout=10
 > git fetch --tags --force --progress git://github.com/LibreELEC/LibreELEC.tv.git +refs/heads/*:refs/remotes/origin/* # timeout=360
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 5c3df44aa7e698f2047ce6d11cecded6495e46b8 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 5c3df44aa7e698f2047ce6d11cecded6495e46b8
Commit message: "Merge pull request #3773 from jernejsk/opi3-fix"
 > git rev-list --no-walk da32fd358a0cbc3457115bcacc71d56623908fb6 # timeout=10
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - Injecting as environment variables the properties file path '/var/lib/jenkins/common.properties'
[EnvInject] - Variables injected successfully.
[RK3328] $ /bin/bash -xe /tmp/jenkins6137980027577121103.sh
+ '[' master '!=' master ']'
+ '[' master '!=' master ']'
+ '[' false == true ']'
+ '[' master '!=' master ']'
+ export JOB=RK3328
+ JOB=RK3328
+ echo RK3328
RK3328
+ rm -Rf env.properties
++ find projects -iname RK3328 -print
++ tail -n 1
++ awk -F/ '{print $4}'
++ tr -d '[:space:]'
+ DEVICE=RK3328
+ '[' -z RK3328 ']'
++ find projects -iname RK3328 -print
++ tail -n 1
++ awk -F/ '{print $2}'
++ tr -d '[:space:]'
+ PROJECT=Rockchip
++ grep -o x86_64 projects/Rockchip/options
++ tr -d '[:space:]'
+ ARCH=
+ '[' -z '' ']'
+ ARCH=arm
+ echo arm
arm
+ echo 'ARCH = arm'
+ echo arm
arm
+ echo 'ARCH = arm'
+ case "${DEVICE}" in
+ export PROJECT=Rockchip
+ PROJECT=Rockchip
+ echo 'PROJECT = Rockchip'
+ export DEVICE=RK3328
+ DEVICE=RK3328
+ echo 'DEVICE = RK3328'
+ export DEF=RK3328
+ DEF=RK3328
+ echo RK3328
RK3328
+ echo 'DEF = RK3328'
++ scripts/uboot_helper Rockchip RK3328
+ MANIFEST='box box-trn9 box-z28 roc-cc rock64 rockbox'
+ case "${MANIFEST}" in
+ U=Y
+ case "${JOB_NAME}" in
++ git rev-list HEAD --count
+ export R=32130
+ R=32130
+ echo 'HEAD = r32130'
++ cat distributions/LibreELEC/version
++ grep OS_VERSION
++ awk '-F"' '{print $2}'
++ tail -n 1
+ export LE_VER=9.80
+ LE_VER=9.80
+ echo 'LE_VER = 9.80'
+ case "${Clean}" in
+ make distclean
rm -rf ./.ccache ./build.*
+ case "${BUILD_CAUSE}" in
+ CONCURRENCY_MAKE_LEVEL=4
+ PERIODIC=nightly
++ date +%w
+ DOW=6
++ date +%U
+ WEEK=33
++ date +%Y
+ WEEKLY=2019
++ date +%Y -d 'last sunday'
+ PRIORWEEK=2019
++ echo 9.80-weekly-201933
+ export WEEKLY=9.80-weekly-201933
+ WEEKLY=9.80-weekly-201933
+ echo 'WEEKLY = 9.80-weekly-201933'
+ export CCACHE_DISABLE=1
+ CCACHE_DISABLE=1
+ echo 'Determine which build server we are on to define SOURCES and TARGET'
Determine which build server we are on to define SOURCES and TARGET
+ case "${ALPHA}" in
+ case "`echo ${NODE_NAME}`" in
++ echo build4
+ SOURCES_DIR=/var/lib/jenkins/LE/build2/sources
+ TARGET_DIR=/var/lib/jenkins/LE/build2/target
+ PROJECT=Rockchip
+ DEVICE=RK3328
+ ARCH=arm
+ SOURCES_DIR=/var/lib/jenkins/LE/build2/sources
+ TARGET_DIR=/var/lib/jenkins/LE/build2/target
+ CONCURRENCY_MAKE_LEVEL=4
+ BUILD_PERIODIC=nightly
+ make image
./scripts/image mkimage

 =================================================================================
 Configuration for LibreELEC (community)
 =================================================================================

 Buildoptions:
 ======================================================
 - CPU (ARCH):				 cortex-a53 (arm)
 - FLOAT:				 hard
 - FPU:					 crypto-neon-fp-armv8
 - CPU features:			 32bit neon
 - LTO (Link Time Optimization) support: yes
 - GOLD (Google Linker) Support:	 yes
 - LLVM support:		
```

The output of this template is `LibreELEC/LibteELEC.tv/env.properties`, which looks like:
```
ARCH = arm
PROJECT = Rockchip
DEVICE = RK3328
DEF = RK3328
HEAD = r32130
LE_VER = 9.80
WEEKLY = 9.80-weekly-201933
```

6. What is reading `env.properties` - is this something else we have written? Or is it being output for documentation purposes?

7. Are there any other "input" parameters to this template - it looks like
```
JOB
BRANCH
ALPHA
ALPHA_VERSION
Clean
BUILD_CAUSE
NODE_NAME
```

8. When "building everything", how is `${JOB}` determined - presumably there is a process (script?) that iterates over all devices?

9. The template uses `NODE_NAME` to determine `TARGET_DIR` and `SOURCE_DIR` variables, which might better come from a static LE/Jenkins/slave.config so that we don't have to special case individual build slaves (and can add new slaves more easily).

**Comment by islipfd19** [comment]
@MilhouseVH - to answer your questions.

1. Jenkins is configured to use bash executable at /bin/bash. That may be linked to sh, or some other shell. Though, as you review the template things may seem unconventional. Jenkins doesn't handle some of the traditional commands used in shell; i.e. the IF statements won't work in a Jenkins build script.

2. Which ever makes it easiest, having the a jenkins.conf in the LE repo where you suggest seems to be the most ideal place.

3. The LE repo is cloned using Jenkins standard method of building. It is configured in a way that allows scheduled jobs to run with defaults and to also allow a user to be able to select parameters thus keeping the number of jobs to a minimum. The env.properties file contains jobs specific parameters which are used to pass along to other parts of the build process for the job that is running. It is the only method to pass variables build during the build phase onto the post build phase.

4. This template is used for the nightly and the alpha builds. There are six other templates *yet to be Pr'd for review) that allow a PR, GIT commit and add-on builds. Each are slightly different based on the need but follow the same construct if you will to keep maintenance of them down.

5. Correct, ${job} with a few of the other variables (${PROJECT}, ${DEVICE}, ${DEF}) controls what device is built. This allows the template to be used per device. The intention is to have Jenkins configured to be able to build one device 

6. The Jenkins job is configured to inject the parameters written to env.properties to be used in the post build phase.

7. Yes, there are other input parameters to the jobs. These parameters are defined when a user starts a job to build. They are a series of questions that give the user flexibility to build what is needed. The ALPHA parameters provide us (or @CvH ) the means to build official images. BUILD_CAUSE is determined if SCM detects changes at GITHUB. NODE_NAME is determined by what slave the jobs is build on.

7. There is no "build everything" script but there is another job that allows someone to "kick" each of the jobs off at once.. Each nightly job is configured to run at a specific time when SCM detects changes on GITHUB.

8. There are additional property files on each slave and master. The files on the slaves are named common.properties and list the target and source patch for TARGET_DIR and SOURCE_DIR. If at all possible, the parameters that are specific to the LE project , i.e. hostname/port should be defined in those files. The other property file is named version and is kept on the master jenkins server. This is build daily and lists all of the possible LE version that can be built.

**Comment by MilhouseVH** [comment]
Would it make sense to move most of the template logic into actual bash scripts (hosted by the Jenkins repo) so that the template is significantly simplified? Then these bash scripts can be shared amongst the different templates.

**Comment by islipfd19** [comment]
Yes, it make sense. The script in the jenkins repo can be used as a wrapper to build each of the images.

**Pull request closed without merging**
